package com.mycompany.views;

public class CalificacionesEstudiantesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EstudiantesJPanel
     */
    public CalificacionesEstudiantesJPanel() {
        initComponents();
        initStyles();
    }

    private void initStyles() {
        btnPrimerParcial.putClientProperty("FlatLaf.style", "Font: bold $h1.regular.font");
        btnSegundoParcial.putClientProperty("FlatLaf.style", "Font: bold $h1.regular.font");
        btnTercerParcial.putClientProperty("FlatLaf.style", "Font: bold $h1.regular.font");
        btnCuartoParcial.putClientProperty("FlatLaf.style", "Font: bold $h1.regular.font");
        btnVerPrimerParcial.putClientProperty("FlatLaf.style", "Font: bold $h1.regular.font");
        btnVerSegundoParcial.putClientProperty("FlatLaf.style", "Font: bold $h1.regular.font");
        btnVerTercerParcial.putClientProperty("FlatLaf.style", "Font: bold $h1.regular.font");
        btnVerCuartoParcial.putClientProperty("FlatLaf.style", "Font: bold $h1.regular.font");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPrimerParcial = new javax.swing.JButton();
        btnSegundoParcial = new javax.swing.JButton();
        btnTercerParcial = new javax.swing.JButton();
        btnCuartoParcial = new javax.swing.JButton();
        btnVerPrimerParcial = new javax.swing.JButton();
        btnVerSegundoParcial = new javax.swing.JButton();
        btnVerTercerParcial = new javax.swing.JButton();
        btnVerCuartoParcial = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));

        jPanel1.setBackground(new java.awt.Color(52, 52, 52));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrimerParcial.setBackground(new java.awt.Color(255, 153, 0));
        btnPrimerParcial.setForeground(new java.awt.Color(255, 255, 255));
        btnPrimerParcial.setText("Primer Parcial");
        btnPrimerParcial.setBorder(null);
        btnPrimerParcial.setBorderPainted(false);
        btnPrimerParcial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrimerParcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimerParcialActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrimerParcial, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 220, 60));

        btnSegundoParcial.setBackground(new java.awt.Color(255, 153, 0));
        btnSegundoParcial.setForeground(new java.awt.Color(255, 255, 255));
        btnSegundoParcial.setText("Segundo Parcial");
        btnSegundoParcial.setBorder(null);
        btnSegundoParcial.setBorderPainted(false);
        btnSegundoParcial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSegundoParcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSegundoParcialActionPerformed(evt);
            }
        });
        jPanel1.add(btnSegundoParcial, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 220, 60));

        btnTercerParcial.setBackground(new java.awt.Color(255, 153, 0));
        btnTercerParcial.setForeground(new java.awt.Color(255, 255, 255));
        btnTercerParcial.setText("Tercer Parcial");
        btnTercerParcial.setBorder(null);
        btnTercerParcial.setBorderPainted(false);
        btnTercerParcial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTercerParcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTercerParcialActionPerformed(evt);
            }
        });
        jPanel1.add(btnTercerParcial, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 220, 60));

        btnCuartoParcial.setBackground(new java.awt.Color(255, 153, 0));
        btnCuartoParcial.setForeground(new java.awt.Color(255, 255, 255));
        btnCuartoParcial.setText("Cuarto Parcial");
        btnCuartoParcial.setBorder(null);
        btnCuartoParcial.setBorderPainted(false);
        btnCuartoParcial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCuartoParcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuartoParcialActionPerformed(evt);
            }
        });
        jPanel1.add(btnCuartoParcial, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 220, 60));

        btnVerPrimerParcial.setBackground(new java.awt.Color(255, 153, 0));
        btnVerPrimerParcial.setForeground(new java.awt.Color(255, 255, 255));
        btnVerPrimerParcial.setText("Ver Calificaciones Primer Parcial");
        btnVerPrimerParcial.setBorder(null);
        btnVerPrimerParcial.setBorderPainted(false);
        btnVerPrimerParcial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerPrimerParcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPrimerParcialActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerPrimerParcial, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 330, 60));

        btnVerSegundoParcial.setBackground(new java.awt.Color(255, 153, 0));
        btnVerSegundoParcial.setForeground(new java.awt.Color(255, 255, 255));
        btnVerSegundoParcial.setText("Ver Calificaciones Segundo Parcial");
        btnVerSegundoParcial.setBorder(null);
        btnVerSegundoParcial.setBorderPainted(false);
        btnVerSegundoParcial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerSegundoParcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerSegundoParcialActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerSegundoParcial, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 330, 60));

        btnVerTercerParcial.setBackground(new java.awt.Color(255, 153, 0));
        btnVerTercerParcial.setForeground(new java.awt.Color(255, 255, 255));
        btnVerTercerParcial.setText("Ver Calificaciones Tercer Parcial");
        btnVerTercerParcial.setBorder(null);
        btnVerTercerParcial.setBorderPainted(false);
        btnVerTercerParcial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerTercerParcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTercerParcialActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerTercerParcial, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 330, 60));

        btnVerCuartoParcial.setBackground(new java.awt.Color(255, 153, 0));
        btnVerCuartoParcial.setForeground(new java.awt.Color(255, 255, 255));
        btnVerCuartoParcial.setText("Ver Calificaciones Cuarto Parcial");
        btnVerCuartoParcial.setBorder(null);
        btnVerCuartoParcial.setBorderPainted(false);
        btnVerCuartoParcial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerCuartoParcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCuartoParcialActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerCuartoParcial, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 330, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrimerParcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimerParcialActionPerformed

        MenuPrincipalJFrame.mostrarJPanel(new PrimerParcialJPanel());
    }//GEN-LAST:event_btnPrimerParcialActionPerformed

    private void btnSegundoParcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSegundoParcialActionPerformed

        MenuPrincipalJFrame.mostrarJPanel(new SegundoParcialJPanel());
    }//GEN-LAST:event_btnSegundoParcialActionPerformed

    private void btnTercerParcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTercerParcialActionPerformed

        MenuPrincipalJFrame.mostrarJPanel(new TercerParcialJPanel());

    }//GEN-LAST:event_btnTercerParcialActionPerformed

    private void btnCuartoParcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuartoParcialActionPerformed

        MenuPrincipalJFrame.mostrarJPanel(new CuartoParcialJPanel());

    }//GEN-LAST:event_btnCuartoParcialActionPerformed

    private void btnVerPrimerParcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPrimerParcialActionPerformed

        MenuPrincipalJFrame.mostrarJPanel(new VerCalificacionesPrimerParcial());
    }//GEN-LAST:event_btnVerPrimerParcialActionPerformed

    private void btnVerCuartoParcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCuartoParcialActionPerformed

        MenuPrincipalJFrame.mostrarJPanel(new VerCalificacionesCuartoParcial());

    }//GEN-LAST:event_btnVerCuartoParcialActionPerformed

    private void btnVerTercerParcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTercerParcialActionPerformed

        MenuPrincipalJFrame.mostrarJPanel(new VerCalificacionesTercerParcial());

    }//GEN-LAST:event_btnVerTercerParcialActionPerformed

    private void btnVerSegundoParcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSegundoParcialActionPerformed

        MenuPrincipalJFrame.mostrarJPanel(new VerCalificacionesSegundoParcial());

    }//GEN-LAST:event_btnVerSegundoParcialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCuartoParcial;
    private javax.swing.JButton btnPrimerParcial;
    private javax.swing.JButton btnSegundoParcial;
    private javax.swing.JButton btnTercerParcial;
    private javax.swing.JButton btnVerCuartoParcial;
    private javax.swing.JButton btnVerPrimerParcial;
    private javax.swing.JButton btnVerSegundoParcial;
    private javax.swing.JButton btnVerTercerParcial;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
