/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.modelos.Estudiante;
import com.mycompany.sistemadeestudiantes.DAOEstudianteImpl;
import com.mycompany.utils.Utils;
import com.mycompany.intefaces.DAOEstudiante;

/**
 *
 * @author nbmmll nnnnn
 */
public class MatricularEstudiantesJPanel extends javax.swing.JPanel {

    boolean edicion = false;
    Estudiante edicionEstudiante;

    public MatricularEstudiantesJPanel() {
        initComponents();
        initStyles();
    }

    public MatricularEstudiantesJPanel(Estudiante estudiante) {
        initComponents();
        edicion = true;
        edicionEstudiante = estudiante;
        initStyles();
    }

    private void initStyles() {
        titulo.putClientProperty("FlatLaf.styleClass", "Font: bold $h1.regular.font");
        nombreTxt.putClientProperty("JTextField.placeholderText", "Ingrese el nombre del alumno. ");
        identidadTxt.putClientProperty("JTextFiel.placeholderText", "Ingrese la identidad del alumno. ");
        apellidoPaternoTxt.putClientProperty("JTextField.placeholderText", "Ingrese el apellido paterno del alumno. ");
        apellidoMaternoTxt.putClientProperty("JTextField.placeholderText", "Ingrese el apellido materno del alumno. ");
        gradoTxt.putClientProperty("JTextField.placeholderText", "Ingrese el grado del alumno. ");
        encargadoTxt.putClientProperty("JTextField.placeholderText", "Ingrese el encargado del alumno. ");
        telEncargadoTxt.putClientProperty("JTextField.placeholderText", "Ingrese el número teléfonico del encargado. ");
        observacionMedicaTxt.putClientProperty("JTextField.placeholderText", "Ingrese si el alumno tiene alguna observación médica. ");
        btnMatricular.putClientProperty("FlatLaf.style", "font: bold $h1.regular.font");

        if (edicion) {
            titulo1.setText("Editar Estudiante. ");
            btnMatricular.setText("Guardar");

            if (edicionEstudiante != null) {
                identidadTxt.setEnabled(false);
                nombreTxt.setText(edicionEstudiante.getNombre());
                identidadTxt.setText(edicionEstudiante.getId() + "");
                apellidoPaternoTxt.setText(edicionEstudiante.getApellidoPaterno());
                apellidoMaternoTxt.setText(edicionEstudiante.getApellidoMaterno());
                gradoTxt.setText(edicionEstudiante.getGrado() + "");
                encargadoTxt.setText(edicionEstudiante.getEncargado());
                telEncargadoTxt.setText(edicionEstudiante.getTelEncargado());
                observacionMedicaTxt.setText(edicionEstudiante.getObservacionMedica());
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        titulo2 = new javax.swing.JLabel();
        identidadTxt = new javax.swing.JTextField();
        apellidoMaternoTxt = new javax.swing.JTextField();
        titulo3 = new javax.swing.JLabel();
        titulo4 = new javax.swing.JLabel();
        apellidoPaternoTxt = new javax.swing.JTextField();
        titulo5 = new javax.swing.JLabel();
        gradoTxt = new javax.swing.JTextField();
        titulo6 = new javax.swing.JLabel();
        encargadoTxt = new javax.swing.JTextField();
        titulo7 = new javax.swing.JLabel();
        telEncargadoTxt = new javax.swing.JTextField();
        titulo8 = new javax.swing.JLabel();
        observacionMedicaTxt = new javax.swing.JTextField();
        btnMatricular = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));

        background.setBackground(new java.awt.Color(52, 52, 52));
        background.setPreferredSize(new java.awt.Dimension(750, 430));

        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Nombre");

        titulo1.setForeground(new java.awt.Color(255, 255, 255));
        titulo1.setText("Matricular nuevo estudiante");

        nombreTxt.setBackground(new java.awt.Color(52, 52, 52));
        nombreTxt.setForeground(new java.awt.Color(255, 255, 255));
        nombreTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        nombreTxt.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        nombreTxt.setSelectionColor(new java.awt.Color(255, 153, 0));

        titulo2.setForeground(new java.awt.Color(255, 255, 255));
        titulo2.setText("Identidad");

        identidadTxt.setBackground(new java.awt.Color(52, 52, 52));
        identidadTxt.setForeground(new java.awt.Color(255, 255, 255));
        identidadTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        identidadTxt.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        identidadTxt.setSelectionColor(new java.awt.Color(255, 153, 0));
        identidadTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identidadTxtActionPerformed(evt);
            }
        });

        apellidoMaternoTxt.setBackground(new java.awt.Color(52, 52, 52));
        apellidoMaternoTxt.setForeground(new java.awt.Color(255, 255, 255));
        apellidoMaternoTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        apellidoMaternoTxt.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        apellidoMaternoTxt.setSelectionColor(new java.awt.Color(255, 153, 0));

        titulo3.setForeground(new java.awt.Color(255, 255, 255));
        titulo3.setText("Apellido Materno");

        titulo4.setForeground(new java.awt.Color(255, 255, 255));
        titulo4.setText("Apellido Paterno");

        apellidoPaternoTxt.setBackground(new java.awt.Color(52, 52, 52));
        apellidoPaternoTxt.setForeground(new java.awt.Color(255, 255, 255));
        apellidoPaternoTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        apellidoPaternoTxt.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        apellidoPaternoTxt.setSelectionColor(new java.awt.Color(255, 153, 0));

        titulo5.setForeground(new java.awt.Color(255, 255, 255));
        titulo5.setText("Grado");

        gradoTxt.setBackground(new java.awt.Color(52, 52, 52));
        gradoTxt.setForeground(new java.awt.Color(255, 255, 255));
        gradoTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        gradoTxt.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        gradoTxt.setSelectionColor(new java.awt.Color(255, 153, 0));

        titulo6.setForeground(new java.awt.Color(255, 255, 255));
        titulo6.setText("Encargado");

        encargadoTxt.setBackground(new java.awt.Color(52, 52, 52));
        encargadoTxt.setForeground(new java.awt.Color(255, 255, 255));
        encargadoTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        encargadoTxt.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        encargadoTxt.setSelectionColor(new java.awt.Color(255, 153, 0));

        titulo7.setForeground(new java.awt.Color(255, 255, 255));
        titulo7.setText("Tel. Encargado");

        telEncargadoTxt.setBackground(new java.awt.Color(52, 52, 52));
        telEncargadoTxt.setForeground(new java.awt.Color(255, 255, 255));
        telEncargadoTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        telEncargadoTxt.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        telEncargadoTxt.setSelectionColor(new java.awt.Color(255, 153, 0));

        titulo8.setForeground(new java.awt.Color(255, 255, 255));
        titulo8.setText("Observación Médica");

        observacionMedicaTxt.setBackground(new java.awt.Color(52, 52, 52));
        observacionMedicaTxt.setForeground(new java.awt.Color(255, 255, 255));
        observacionMedicaTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        observacionMedicaTxt.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        observacionMedicaTxt.setSelectionColor(new java.awt.Color(255, 153, 0));

        btnMatricular.setBackground(new java.awt.Color(255, 153, 0));
        btnMatricular.setForeground(new java.awt.Color(255, 255, 255));
        btnMatricular.setText("Matricular");
        btnMatricular.setBorder(null);
        btnMatricular.setBorderPainted(false);
        btnMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatricularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(titulo5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(gradoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(titulo6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(identidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(encargadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(titulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(titulo7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(apellidoPaternoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(telEncargadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(titulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(titulo8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(apellidoMaternoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(observacionMedicaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(btnMatricular, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(titulo1)
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(titulo5)))
                .addGap(4, 4, 4)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(gradoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo2)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(titulo6)))
                .addGap(4, 4, 4)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(identidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(encargadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo4)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(titulo7)))
                .addGap(4, 4, 4)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apellidoPaternoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(telEncargadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo3)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(titulo8)))
                .addGap(4, 4, 4)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apellidoMaternoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(observacionMedicaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(btnMatricular, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatricularActionPerformed

        String nombre = nombreTxt.getText();
        String id = identidadTxt.getText();
        String apellidoP = apellidoPaternoTxt.getText();
        String apellidoM = apellidoMaternoTxt.getText();
        String grado = gradoTxt.getText();
        String encargado = encargadoTxt.getText();
        String telEncargado = telEncargadoTxt.getText();
        String observacionMed = observacionMedicaTxt.getText();

        if (nombre.isEmpty() || id.isEmpty() || apellidoP.isEmpty() || apellidoM.isEmpty() || grado.isEmpty() || encargado.isEmpty()
                || telEncargado.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos. ", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            nombreTxt.requestFocus();
            return;
        } else if (!Utils.isNumeric(grado)) {
            javax.swing.JOptionPane.showMessageDialog(this, "El grado es un número entero. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            identidadTxt.requestFocus();
            return;
        } else if (identidadTxt.getText().length() > 13 || identidadTxt.getText().length() < 13) {
            javax.swing.JOptionPane.showMessageDialog(this, "La longitud de la identidad es de 13 números. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        Estudiante estudiante = edicion ? edicionEstudiante : new Estudiante();
        estudiante.setNombre(nombre);
        estudiante.setId(id);
        estudiante.setApellidoPaterno(apellidoP);
        estudiante.setApellidoMaterno(apellidoM);
        estudiante.setGrado(Integer.parseInt(grado));
        estudiante.setEncargado(encargado);
        estudiante.setTelEncargado(telEncargado);
        estudiante.setObservacionMedica(observacionMed);
        try {
            DAOEstudiante dao = new DAOEstudianteImpl();
            if (!edicion) {
                dao.matricular(estudiante);
            } else {
                dao.editar(estudiante);
            }
            String mensajeExito = edicion ? "editado" : "matriculado";
            javax.swing.JOptionPane.showMessageDialog(this, "Alumno " + mensajeExito + " con éxito. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            if (!edicion) {

                nombreTxt.setText("");
                identidadTxt.setText("");
                apellidoPaternoTxt.setText("");
                apellidoMaternoTxt.setText("");
                gradoTxt.setText("");
                encargadoTxt.setText("");
                telEncargadoTxt.setText("");
                observacionMedicaTxt.setText("");
            }
        } catch (Exception e) {
            String mensajeError = edicion ? "editar" : "matricular";
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al " + mensajeError + " el estudiante. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnMatricularActionPerformed

    private void identidadTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identidadTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identidadTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoMaternoTxt;
    private javax.swing.JTextField apellidoPaternoTxt;
    private javax.swing.JPanel background;
    private javax.swing.JButton btnMatricular;
    private javax.swing.JTextField encargadoTxt;
    private javax.swing.JTextField gradoTxt;
    private javax.swing.JTextField identidadTxt;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JTextField observacionMedicaTxt;
    private javax.swing.JTextField telEncargadoTxt;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo3;
    private javax.swing.JLabel titulo4;
    private javax.swing.JLabel titulo5;
    private javax.swing.JLabel titulo6;
    private javax.swing.JLabel titulo7;
    private javax.swing.JLabel titulo8;
    // End of variables declaration//GEN-END:variables
}
